### ISSUE TITLE
FRONTEND: Parameters sort order (frontend)

### ISSUE THREAD

**Issue by earlgreyness** [JURISTAILY/speaker-split#1]
# We need to change the sort order

![screenshot_2017-02-24_13-13-03](https://cloud.githubusercontent.com/assets/24636214/23299597/26cd2a7a-fa93-11e6-8c7f-488db18bfc7a.png)

The list of parameters must be sorted on frontend. Sort order is determined by parameter's grade: lowest on top. Visually: from red to green, top to bottom.

**Comment by BOPOHOB** [comment]
Может где-нибудь ещё сделать выключатель для сортировки?
