### ISSUE TITLE
FRONTEND: Настроить выбор пайпов для параметров звонка

### ISSUE THREAD

**Issue by earlgreyness** [JURISTAILY/speaker-split#2]
# Сейчас:
![screenshot_2017-02-24_13-24-18](https://cloud.githubusercontent.com/assets/24636214/23299989/abd5d73e-fa94-11e6-8468-cae87e7370aa.png)

# Нужно:
![screenshot_2017-02-24_13-29-31](https://cloud.githubusercontent.com/assets/24636214/23300134/4c120006-fa95-11e6-89dc-61dc3fca6135.png)

**Comment by earlgreyness** [comment]
Это касается всех параметров, выражающих какие-либо доли.

**Comment by earlgreyness** [comment]
Принципиальный момент: это должно быть на фронте обязательно. С бека приходят в формате float, нормированном на единицу.

**Comment by BOPOHOB** [comment]
не может быть бага у фичи, которую ещё никто не делал. Значения для всех параметров на данный момент попадают как есть, без прохождения через пайп. Пока закрываю ишью. Сегодня-завтра сделаю систему выбора пайпов для значений параметров внутри таблицы, учту описанную задачу.

**Comment by BOPOHOB** [comment]
Теперь система такая: если у name_rus в таблице parameters_meta есть окончание ", сек", ", %" или ", шт", будет выбран соответствующий пайп. Иначе будет проанализировано окончание поля name по вариантам "_duration", "_ratio" или "_count". Если ничто из этого не намекнёт на верный пайп, значение будет отображено как число с округлением до одного знака после запятой
